networks:
 bitwarden:
  external:
    name: bitwarden

services:
  vaultwarden:
   image: vaultwarden/server:latest
   deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: "256M"
   restart: always
   ports:
     - 80:80
   networks:
    - bitwarden
   volumes:
     - ${VAULTWARDEN_DATA_PATH}:/data
  nginx:
   image: nginx
   deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: "256M"
   restart: always
   ports:
     - 8080:8080
     #- 8443:8443
   networks:
    - bitwarden
   volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf